# Generated by Django 4.2 on 2024-09-03 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_wallets_owner'),
        ('buys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buys',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.users'),
        ),
    ]
