# Generated by Django 4.2 on 2024-08-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costs',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='costs',
            name='status',
        ),
        migrations.RemoveField(
            model_name='costs',
            name='time_create',
        ),
        migrations.AddField(
            model_name='costs',
            name='frequency',
            field=models.CharField(choices=[('ND', 'custom number of days'), ('ED', 'every day'), ('EW', 'every week'), ('EM', 'every month'), ('EY', 'every year')], default='EM', max_length=3),
        ),
        migrations.AddField(
            model_name='costs',
            name='owner',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='costs',
            name='recipient',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='costs',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
