# Generated by Django 4.2 on 2024-09-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0004_alter_costs_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='owner',
            field=models.IntegerField(),
        ),
    ]
