# Generated by Django 4.2 on 2024-09-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0006_alter_costs_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='frequency',
            field=models.CharField(choices=[('WR', 'reminder'), ('ED', 'every day'), ('EW', 'every week'), ('EM', 'every month'), ('EY', 'every year')], default='EM', max_length=3),
        ),
    ]
