# Generated by Django 4.2 on 2024-08-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='wallets',
            name='owner',
            field=models.IntegerField(unique=True),
        ),
    ]
