# Generated by Django 4.2 on 2024-09-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_users_email_alter_users_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.CharField(default='user'),
        ),
    ]
